### PR TITLE
Throws to Try-With-Resources, Fix part of issues Fixes #108,110,130

### LINKED ISSUE #108: Replace occurrences of "throws Exception"
There are many occurrences of `throws Exception` throughout the code.  This is bad design.  Each one needs to be changed to `throws` followed by a list of one or more specific exception types which are thrown from that particular method.  This issue applies to occurrences under `src`.  Those under `Test` will need to be handled in conjunction with a more comprehensive rework of the test suite, which will be driven by a different issue.

### PR DESCRIPTION
**Pull request by Fahad-n**
part of Fixes #108 #110 #130

### CODE REVIEW

File: src/Controller/MainController.java [hunk 1]
```diff
@@ -74,6 +74,7 @@ public static void initialise()
                 CipherInputStream cipherInputStream = new CipherInputStream(new BufferedInputStream(new FileInputStream(fileName)), cipher);
                 ObjectInputStream inputStream = new ObjectInputStream(cipherInputStream);
                 SealedObject sealedObject = (SealedObject) inputStream.readObject();
+                inputStream.close();
```
Comment (rsanchez-wsu) [inline src/Controller/MainController.java]: As I mentioned in class, the appropriate way to handle this is by managing the resource in a try-with-resources.

Comment (Fahad-n) [reply src/Controller/MainController.java]: But it is already using try-catch.

Comment (rsanchez-wsu) [reply src/Controller/MainController.java]: That may be the case, but try-with-resources is the better construct for this.  There are several things inside of the try block that do not really need to be there and if you rework it as a try-with-resources it will be apparent.

**Comment by Fahad-n** [comment]
How about this one ?

**Comment by Fahad-n** [comment]
I forgot to put [finally] after the catch statements and close the object, what do you think?

**Comment by Fahad-n** [comment]
it is now fixed in my fork do you see it here?

File: src/Controller/MainController.java [hunk 2]
```diff
@@ -62,27 +41,22 @@ public static StudyPlannerController getSPC()
...
      */
     public static void initialise()
-    {
-        File plannerFile = new File("StudyPlanner.dat");
+    { 
         try
         {
+        	Cipher cipher = Cipher.getInstance("Blowfish");
+        	cipher.init(Cipher.DECRYPT_MODE, key64);
+        try (
```
Comment (rsanchez-wsu) [inline src/Controller/MainController.java]: The indentation level of this line is incorrect.

File: src/Controller/MainController.java [hunk 3]
```diff
@@ -62,27 +41,22 @@ public static StudyPlannerController getSPC()
      * importing an existing Study Planner file.
      */
     public static void initialise()
-    {
-        File plannerFile = new File("StudyPlanner.dat");
+    { 
         try
         {
+        	Cipher cipher = Cipher.getInstance("Blowfish");
```
Comment (rsanchez-wsu) [inline src/Controller/MainController.java]: These two lines mix spaces and tabs.  You should use only tabs.

File: src/Controller/MainController.java [hunk 4]
```diff
@@ -62,27 +41,22 @@ public static StudyPlannerController getSPC()
...
+        	cipher.init(Cipher.DECRYPT_MODE, key64);
+        try (
+        		CipherInputStream cipherInputStream = new CipherInputStream(new BufferedInputStream(new FileInputStream(fileName)), cipher);
+        		ObjectInputStream inputStream = new ObjectInputStream(cipherInputStream);
+            )
+        {
```
Comment (rsanchez-wsu) [inline src/Controller/MainController.java]: The indentation level of this line is incorrect

File: src/Controller/MainController.java [hunk 5]
```diff
@@ -1,24 +1,3 @@
-/*
```
Comment (rsanchez-wsu) [inline src/Controller/MainController.java]: Please restore the file's license header.

**Comment by rsanchez-wsu** [comment]
@Fahad-n Also, please resolve the merge conflict when you update your branch.

**Comment by Fahad-n** [comment]
All done. I was trying to sync my fork but I think I can't while there is a bending pull request, but I managed to fix it anyway. About the Checkstyle it was yelling with yellow before i touch it, i tried to fix it but it keeps getting angry, it doesn't give a useful hints, and I don't think it likes try-with-resources.

**Comment by rsanchez-wsu** [comment]
@Fahad-n You will need to sync the fork, following the GitHub documentation.  You should find that there are conflicts in `MainController.java`.  You will need to resolve those conflicts, make sure that your changes conform to CheckStyle, and then push any new commits on your fork.  At that point you should be able to look at the pull request here and see that it says it can be merged with no conflicts.

**Comment by rsanchez-wsu** [comment]
Please sync your fork, resolve any conflicts with your pull request, and confirm that the Travis build succeeds so that I can review and merge your changes.

**Comment by Fahad-n** [comment]
Done

File: src/Controller/MainController.java [hunk 6]
```diff
@@ -93,63 +93,66 @@ public static void setSpc(StudyPlannerController newSpc) {
...
-				try (CipherInputStream cis = new CipherInputStream(
+			Cipher cipher = Cipher.getInstance("Blowfish");
+			cipher.init(Cipher.DECRYPT_MODE, key64);
+			try (CipherInputStream cis = new CipherInputStream(
 						new BufferedInputStream(new FileInputStream(plannerFile)), cipher);
-						ObjectInputStream ois = new ObjectInputStream(cis)) {
+					ObjectInputStream ois = new ObjectInputStream(cis)) {
 
+				// If a file is present:
+				if (plannerFile.exists()) {
```
Comment (rsanchez-wsu) [inline src/Controller/MainController.java]: What is the benefit of moving this conditional inside the try block?  It looks to me like it will create a situation where the creation of the `BufferedInputStream/FileInputStream` might depend upon a non-existent file.

File: src/Controller/MainController.java [hunk 7]
```diff
@@ -93,63 +93,66 @@ public static void setSpc(StudyPlannerController newSpc) {
...
 					spc = new StudyPlannerController((StudyPlanner) sealedObject.getObject(cipher));
 
 					// Sample note
 					if (spc.getPlanner().getCurrentStudyProfile() != null && spc.getPlanner()
 							.getCurrentStudyProfile().getName().equals("First year Gryffindor")) {
 						UIManager.reportSuccess(
-								"Note: This is a pre-loaded sample StudyPlanner, as used by Harry "
-								+ "Potter. To make your own StudyPlanner, restart the application "
-								+ "and choose \"New File\".");
+							"Note: This is a pre-loaded sample StudyPlanner, as used by Harry "
```
Comment (rsanchez-wsu) [inline src/Controller/MainController.java]: The indentation of these lines should not have changed.

File: src/Controller/MainController.java (hunk 6 above)
Comment (Fahad-n) [reply src/Controller/MainController.java]: I did all of these because I thought the nested try has to finish with a direct catch statement that is separated from the other try, and that was in the old java versions as you said. I will fix it with a unique solution.

File: src/Controller/MainController.java (hunk 7 above)
Comment (Fahad-n) [reply src/Controller/MainController.java]: this is because the check style told me to do that. I will fix it

File: src/Controller/MainController.java [hunk 8]
```diff
@@ -91,19 +91,17 @@ public static void setSpc(StudyPlannerController newSpc) {
 	 * importing an existing Study Planner file.
 	 */
 	public static void initialise() {
-		try {
-			ui.showStartup();
-			// If a file is present:
-			if (plannerFile.exists()) {
+		// If a file is present:
```
Comment (rsanchez-wsu) [inline src/Controller/MainController.java]: This comment is not useful.  Please remove it.

File: src/Controller/MainController.java [hunk 9]
```diff
@@ -113,42 +111,43 @@ public static void initialise() {
...
 					}
 				}
-
-			} else {
-				// TODO - fix this, as it is clearly a race condition
-				// This should never happen unless a file changes permissions
-				// or existence in the milliseconds that it runs the above code
-				// after checks in StartupController
-				UIManager.reportError("Failed to load file.");
+			} catch (FileNotFoundException e) {
```
Comment (rsanchez-wsu) [inline src/Controller/MainController.java]: Please remove the "please contact support" from each of these.  I think that you misunderstood something that I said in class.  There are cases where it might be correct to put that into an error message presented to the user.  However, it looks like you have blindly added that to each catch block.  Think about what a user might do if they contacted support in the even of an IllegalBlockSizeException or an InvalidKeyException.

Before we start adding that to exception error messages, we would need a support forum or mailing list where we could direct users.  Right now adding "please contact support" is not giving the user anything actionable.
